package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.thdtek.acs.terminal.bean.NowPicFeatureHexBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOW_PIC_FEATURE_HEX_BEAN".
*/
public class NowPicFeatureHexBeanDao extends AbstractDao<NowPicFeatureHexBean, Long> {

    public static final String TABLENAME = "NOW_PIC_FEATURE_HEX_BEAN";

    /**
     * Properties of entity NowPicFeatureHexBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AuthorityId = new Property(1, long.class, "authorityId", false, "AUTHORITY_ID");
        public final static Property PersonId = new Property(2, long.class, "personId", false, "PERSON_ID");
        public final static Property LastIndex = new Property(3, int.class, "lastIndex", false, "LAST_INDEX");
        public final static Property NowPicOneHex = new Property(4, String.class, "nowPicOneHex", false, "NOW_PIC_ONE_HEX");
        public final static Property NowPicTwoHex = new Property(5, String.class, "nowPicTwoHex", false, "NOW_PIC_TWO_HEX");
        public final static Property NowPicThreeHex = new Property(6, String.class, "nowPicThreeHex", false, "NOW_PIC_THREE_HEX");
    };


    public NowPicFeatureHexBeanDao(DaoConfig config) {
        super(config);
    }
    
    public NowPicFeatureHexBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOW_PIC_FEATURE_HEX_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"AUTHORITY_ID\" INTEGER NOT NULL ," + // 1: authorityId
                "\"PERSON_ID\" INTEGER NOT NULL ," + // 2: personId
                "\"LAST_INDEX\" INTEGER NOT NULL ," + // 3: lastIndex
                "\"NOW_PIC_ONE_HEX\" TEXT," + // 4: nowPicOneHex
                "\"NOW_PIC_TWO_HEX\" TEXT," + // 5: nowPicTwoHex
                "\"NOW_PIC_THREE_HEX\" TEXT);"); // 6: nowPicThreeHex
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOW_PIC_FEATURE_HEX_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NowPicFeatureHexBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getAuthorityId());
        stmt.bindLong(3, entity.getPersonId());
        stmt.bindLong(4, entity.getLastIndex());
 
        String nowPicOneHex = entity.getNowPicOneHex();
        if (nowPicOneHex != null) {
            stmt.bindString(5, nowPicOneHex);
        }
 
        String nowPicTwoHex = entity.getNowPicTwoHex();
        if (nowPicTwoHex != null) {
            stmt.bindString(6, nowPicTwoHex);
        }
 
        String nowPicThreeHex = entity.getNowPicThreeHex();
        if (nowPicThreeHex != null) {
            stmt.bindString(7, nowPicThreeHex);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NowPicFeatureHexBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getAuthorityId());
        stmt.bindLong(3, entity.getPersonId());
        stmt.bindLong(4, entity.getLastIndex());
 
        String nowPicOneHex = entity.getNowPicOneHex();
        if (nowPicOneHex != null) {
            stmt.bindString(5, nowPicOneHex);
        }
 
        String nowPicTwoHex = entity.getNowPicTwoHex();
        if (nowPicTwoHex != null) {
            stmt.bindString(6, nowPicTwoHex);
        }
 
        String nowPicThreeHex = entity.getNowPicThreeHex();
        if (nowPicThreeHex != null) {
            stmt.bindString(7, nowPicThreeHex);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NowPicFeatureHexBean readEntity(Cursor cursor, int offset) {
        NowPicFeatureHexBean entity = new NowPicFeatureHexBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // authorityId
            cursor.getLong(offset + 2), // personId
            cursor.getInt(offset + 3), // lastIndex
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // nowPicOneHex
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // nowPicTwoHex
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // nowPicThreeHex
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NowPicFeatureHexBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAuthorityId(cursor.getLong(offset + 1));
        entity.setPersonId(cursor.getLong(offset + 2));
        entity.setLastIndex(cursor.getInt(offset + 3));
        entity.setNowPicOneHex(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setNowPicTwoHex(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setNowPicThreeHex(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NowPicFeatureHexBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NowPicFeatureHexBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
