package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.thdtek.acs.terminal.bean.TestBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEST_BEAN".
*/
public class TestBeanDao extends AbstractDao<TestBean, Long> {

    public static final String TABLENAME = "TEST_BEAN";

    /**
     * Properties of entity TestBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CameraDetectType = new Property(1, int.class, "cameraDetectType", false, "CAMERA_DETECT_TYPE");
        public final static Property FaceFeaturePairNumber = new Property(2, double.class, "faceFeaturePairNumber", false, "FACE_FEATURE_PAIR_NUMBER");
        public final static Property FaceFeaturePairSuccessOrFailWaitTime = new Property(3, int.class, "faceFeaturePairSuccessOrFailWaitTime", false, "FACE_FEATURE_PAIR_SUCCESS_OR_FAIL_WAIT_TIME");
        public final static Property OpenDoorType = new Property(4, int.class, "openDoorType", false, "OPEN_DOOR_TYPE");
        public final static Property OpenDoorContinueTime = new Property(5, int.class, "openDoorContinueTime", false, "OPEN_DOOR_CONTINUE_TIME");
        public final static Property DoorType = new Property(6, int.class, "doorType", false, "DOOR_TYPE");
        public final static Property DeviceName = new Property(7, String.class, "deviceName", false, "DEVICE_NAME");
        public final static Property DeviceSerialNumber = new Property(8, String.class, "deviceSerialNumber", false, "DEVICE_SERIAL_NUMBER");
        public final static Property DeviceDefendStartTime = new Property(9, String.class, "deviceDefendStartTime", false, "DEVICE_DEFEND_START_TIME");
        public final static Property DeviceDefendEndTime = new Property(10, String.class, "deviceDefendEndTime", false, "DEVICE_DEFEND_END_TIME");
        public final static Property DeviceIntoOrOut = new Property(11, int.class, "deviceIntoOrOut", false, "DEVICE_INTO_OR_OUT");
        public final static Property DeviceMusicSize = new Property(12, int.class, "deviceMusicSize", false, "DEVICE_MUSIC_SIZE");
        public final static Property AppWelcomeMsg = new Property(13, String.class, "appWelcomeMsg", false, "APP_WELCOME_MSG");
        public final static Property AppWelcomeMusic = new Property(14, String.class, "appWelcomeMusic", false, "APP_WELCOME_MUSIC");
        public final static Property ServerIp = new Property(15, String.class, "serverIp", false, "SERVER_IP");
        public final static Property ServerPort = new Property(16, int.class, "serverPort", false, "SERVER_PORT");
        public final static Property DeviceNetworkType = new Property(17, int.class, "deviceNetworkType", false, "DEVICE_NETWORK_TYPE");
        public final static Property DeviceNetworkIpType = new Property(18, int.class, "deviceNetworkIpType", false, "DEVICE_NETWORK_IP_TYPE");
        public final static Property DeviceIpAddress = new Property(19, String.class, "deviceIpAddress", false, "DEVICE_IP_ADDRESS");
        public final static Property DeviceSn = new Property(20, String.class, "deviceSn", false, "DEVICE_SN");
        public final static Property DeviceServiceTime = new Property(21, int.class, "deviceServiceTime", false, "DEVICE_SERVICE_TIME");
        public final static Property DeviceRegisterTime = new Property(22, String.class, "deviceRegisterTime", false, "DEVICE_REGISTER_TIME");
        public final static Property DeviceRomSize = new Property(23, String.class, "deviceRomSize", false, "DEVICE_ROM_SIZE");
        public final static Property DeviceRomAvailableSize = new Property(24, String.class, "deviceRomAvailableSize", false, "DEVICE_ROM_AVAILABLE_SIZE");
        public final static Property DeviceRamMaxSize = new Property(25, String.class, "deviceRamMaxSize", false, "DEVICE_RAM_MAX_SIZE");
        public final static Property DeviceRamTotalSize = new Property(26, String.class, "deviceRamTotalSize", false, "DEVICE_RAM_TOTAL_SIZE");
        public final static Property DeviceRamUseSize = new Property(27, String.class, "deviceRamUseSize", false, "DEVICE_RAM_USE_SIZE");
        public final static Property DeviceCpuTemperature = new Property(28, int.class, "deviceCpuTemperature", false, "DEVICE_CPU_TEMPERATURE");
        public final static Property DeviceTemperature = new Property(29, int.class, "deviceTemperature", false, "DEVICE_TEMPERATURE");
        public final static Property DeviceSystemVersion = new Property(30, String.class, "deviceSystemVersion", false, "DEVICE_SYSTEM_VERSION");
        public final static Property DeviceAppVersion = new Property(31, String.class, "deviceAppVersion", false, "DEVICE_APP_VERSION");
        public final static Property DeviceCameraSdkVersion = new Property(32, String.class, "deviceCameraSdkVersion", false, "DEVICE_CAMERA_SDK_VERSION");
        public final static Property DeviceHardwareSdkVersion = new Property(33, String.class, "deviceHardwareSdkVersion", false, "DEVICE_HARDWARE_SDK_VERSION");
        public final static Property DeviceElapsedRealtime = new Property(34, String.class, "deviceElapsedRealtime", false, "DEVICE_ELAPSED_REALTIME");
    };


    public TestBeanDao(DaoConfig config) {
        super(config);
    }
    
    public TestBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEST_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CAMERA_DETECT_TYPE\" INTEGER NOT NULL ," + // 1: cameraDetectType
                "\"FACE_FEATURE_PAIR_NUMBER\" REAL NOT NULL ," + // 2: faceFeaturePairNumber
                "\"FACE_FEATURE_PAIR_SUCCESS_OR_FAIL_WAIT_TIME\" INTEGER NOT NULL ," + // 3: faceFeaturePairSuccessOrFailWaitTime
                "\"OPEN_DOOR_TYPE\" INTEGER NOT NULL ," + // 4: openDoorType
                "\"OPEN_DOOR_CONTINUE_TIME\" INTEGER NOT NULL ," + // 5: openDoorContinueTime
                "\"DOOR_TYPE\" INTEGER NOT NULL ," + // 6: doorType
                "\"DEVICE_NAME\" TEXT," + // 7: deviceName
                "\"DEVICE_SERIAL_NUMBER\" TEXT," + // 8: deviceSerialNumber
                "\"DEVICE_DEFEND_START_TIME\" TEXT," + // 9: deviceDefendStartTime
                "\"DEVICE_DEFEND_END_TIME\" TEXT," + // 10: deviceDefendEndTime
                "\"DEVICE_INTO_OR_OUT\" INTEGER NOT NULL ," + // 11: deviceIntoOrOut
                "\"DEVICE_MUSIC_SIZE\" INTEGER NOT NULL ," + // 12: deviceMusicSize
                "\"APP_WELCOME_MSG\" TEXT," + // 13: appWelcomeMsg
                "\"APP_WELCOME_MUSIC\" TEXT," + // 14: appWelcomeMusic
                "\"SERVER_IP\" TEXT," + // 15: serverIp
                "\"SERVER_PORT\" INTEGER NOT NULL ," + // 16: serverPort
                "\"DEVICE_NETWORK_TYPE\" INTEGER NOT NULL ," + // 17: deviceNetworkType
                "\"DEVICE_NETWORK_IP_TYPE\" INTEGER NOT NULL ," + // 18: deviceNetworkIpType
                "\"DEVICE_IP_ADDRESS\" TEXT," + // 19: deviceIpAddress
                "\"DEVICE_SN\" TEXT," + // 20: deviceSn
                "\"DEVICE_SERVICE_TIME\" INTEGER NOT NULL ," + // 21: deviceServiceTime
                "\"DEVICE_REGISTER_TIME\" TEXT," + // 22: deviceRegisterTime
                "\"DEVICE_ROM_SIZE\" TEXT," + // 23: deviceRomSize
                "\"DEVICE_ROM_AVAILABLE_SIZE\" TEXT," + // 24: deviceRomAvailableSize
                "\"DEVICE_RAM_MAX_SIZE\" TEXT," + // 25: deviceRamMaxSize
                "\"DEVICE_RAM_TOTAL_SIZE\" TEXT," + // 26: deviceRamTotalSize
                "\"DEVICE_RAM_USE_SIZE\" TEXT," + // 27: deviceRamUseSize
                "\"DEVICE_CPU_TEMPERATURE\" INTEGER NOT NULL ," + // 28: deviceCpuTemperature
                "\"DEVICE_TEMPERATURE\" INTEGER NOT NULL ," + // 29: deviceTemperature
                "\"DEVICE_SYSTEM_VERSION\" TEXT," + // 30: deviceSystemVersion
                "\"DEVICE_APP_VERSION\" TEXT," + // 31: deviceAppVersion
                "\"DEVICE_CAMERA_SDK_VERSION\" TEXT," + // 32: deviceCameraSdkVersion
                "\"DEVICE_HARDWARE_SDK_VERSION\" TEXT," + // 33: deviceHardwareSdkVersion
                "\"DEVICE_ELAPSED_REALTIME\" TEXT);"); // 34: deviceElapsedRealtime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEST_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TestBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCameraDetectType());
        stmt.bindDouble(3, entity.getFaceFeaturePairNumber());
        stmt.bindLong(4, entity.getFaceFeaturePairSuccessOrFailWaitTime());
        stmt.bindLong(5, entity.getOpenDoorType());
        stmt.bindLong(6, entity.getOpenDoorContinueTime());
        stmt.bindLong(7, entity.getDoorType());
 
        String deviceName = entity.getDeviceName();
        if (deviceName != null) {
            stmt.bindString(8, deviceName);
        }
 
        String deviceSerialNumber = entity.getDeviceSerialNumber();
        if (deviceSerialNumber != null) {
            stmt.bindString(9, deviceSerialNumber);
        }
 
        String deviceDefendStartTime = entity.getDeviceDefendStartTime();
        if (deviceDefendStartTime != null) {
            stmt.bindString(10, deviceDefendStartTime);
        }
 
        String deviceDefendEndTime = entity.getDeviceDefendEndTime();
        if (deviceDefendEndTime != null) {
            stmt.bindString(11, deviceDefendEndTime);
        }
        stmt.bindLong(12, entity.getDeviceIntoOrOut());
        stmt.bindLong(13, entity.getDeviceMusicSize());
 
        String appWelcomeMsg = entity.getAppWelcomeMsg();
        if (appWelcomeMsg != null) {
            stmt.bindString(14, appWelcomeMsg);
        }
 
        String appWelcomeMusic = entity.getAppWelcomeMusic();
        if (appWelcomeMusic != null) {
            stmt.bindString(15, appWelcomeMusic);
        }
 
        String serverIp = entity.getServerIp();
        if (serverIp != null) {
            stmt.bindString(16, serverIp);
        }
        stmt.bindLong(17, entity.getServerPort());
        stmt.bindLong(18, entity.getDeviceNetworkType());
        stmt.bindLong(19, entity.getDeviceNetworkIpType());
 
        String deviceIpAddress = entity.getDeviceIpAddress();
        if (deviceIpAddress != null) {
            stmt.bindString(20, deviceIpAddress);
        }
 
        String deviceSn = entity.getDeviceSn();
        if (deviceSn != null) {
            stmt.bindString(21, deviceSn);
        }
        stmt.bindLong(22, entity.getDeviceServiceTime());
 
        String deviceRegisterTime = entity.getDeviceRegisterTime();
        if (deviceRegisterTime != null) {
            stmt.bindString(23, deviceRegisterTime);
        }
 
        String deviceRomSize = entity.getDeviceRomSize();
        if (deviceRomSize != null) {
            stmt.bindString(24, deviceRomSize);
        }
 
        String deviceRomAvailableSize = entity.getDeviceRomAvailableSize();
        if (deviceRomAvailableSize != null) {
            stmt.bindString(25, deviceRomAvailableSize);
        }
 
        String deviceRamMaxSize = entity.getDeviceRamMaxSize();
        if (deviceRamMaxSize != null) {
            stmt.bindString(26, deviceRamMaxSize);
        }
 
        String deviceRamTotalSize = entity.getDeviceRamTotalSize();
        if (deviceRamTotalSize != null) {
            stmt.bindString(27, deviceRamTotalSize);
        }
 
        String deviceRamUseSize = entity.getDeviceRamUseSize();
        if (deviceRamUseSize != null) {
            stmt.bindString(28, deviceRamUseSize);
        }
        stmt.bindLong(29, entity.getDeviceCpuTemperature());
        stmt.bindLong(30, entity.getDeviceTemperature());
 
        String deviceSystemVersion = entity.getDeviceSystemVersion();
        if (deviceSystemVersion != null) {
            stmt.bindString(31, deviceSystemVersion);
        }
 
        String deviceAppVersion = entity.getDeviceAppVersion();
        if (deviceAppVersion != null) {
            stmt.bindString(32, deviceAppVersion);
        }
 
        String deviceCameraSdkVersion = entity.getDeviceCameraSdkVersion();
        if (deviceCameraSdkVersion != null) {
            stmt.bindString(33, deviceCameraSdkVersion);
        }
 
        String deviceHardwareSdkVersion = entity.getDeviceHardwareSdkVersion();
        if (deviceHardwareSdkVersion != null) {
            stmt.bindString(34, deviceHardwareSdkVersion);
        }
 
        String deviceElapsedRealtime = entity.getDeviceElapsedRealtime();
        if (deviceElapsedRealtime != null) {
            stmt.bindString(35, deviceElapsedRealtime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TestBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCameraDetectType());
        stmt.bindDouble(3, entity.getFaceFeaturePairNumber());
        stmt.bindLong(4, entity.getFaceFeaturePairSuccessOrFailWaitTime());
        stmt.bindLong(5, entity.getOpenDoorType());
        stmt.bindLong(6, entity.getOpenDoorContinueTime());
        stmt.bindLong(7, entity.getDoorType());
 
        String deviceName = entity.getDeviceName();
        if (deviceName != null) {
            stmt.bindString(8, deviceName);
        }
 
        String deviceSerialNumber = entity.getDeviceSerialNumber();
        if (deviceSerialNumber != null) {
            stmt.bindString(9, deviceSerialNumber);
        }
 
        String deviceDefendStartTime = entity.getDeviceDefendStartTime();
        if (deviceDefendStartTime != null) {
            stmt.bindString(10, deviceDefendStartTime);
        }
 
        String deviceDefendEndTime = entity.getDeviceDefendEndTime();
        if (deviceDefendEndTime != null) {
            stmt.bindString(11, deviceDefendEndTime);
        }
        stmt.bindLong(12, entity.getDeviceIntoOrOut());
        stmt.bindLong(13, entity.getDeviceMusicSize());
 
        String appWelcomeMsg = entity.getAppWelcomeMsg();
        if (appWelcomeMsg != null) {
            stmt.bindString(14, appWelcomeMsg);
        }
 
        String appWelcomeMusic = entity.getAppWelcomeMusic();
        if (appWelcomeMusic != null) {
            stmt.bindString(15, appWelcomeMusic);
        }
 
        String serverIp = entity.getServerIp();
        if (serverIp != null) {
            stmt.bindString(16, serverIp);
        }
        stmt.bindLong(17, entity.getServerPort());
        stmt.bindLong(18, entity.getDeviceNetworkType());
        stmt.bindLong(19, entity.getDeviceNetworkIpType());
 
        String deviceIpAddress = entity.getDeviceIpAddress();
        if (deviceIpAddress != null) {
            stmt.bindString(20, deviceIpAddress);
        }
 
        String deviceSn = entity.getDeviceSn();
        if (deviceSn != null) {
            stmt.bindString(21, deviceSn);
        }
        stmt.bindLong(22, entity.getDeviceServiceTime());
 
        String deviceRegisterTime = entity.getDeviceRegisterTime();
        if (deviceRegisterTime != null) {
            stmt.bindString(23, deviceRegisterTime);
        }
 
        String deviceRomSize = entity.getDeviceRomSize();
        if (deviceRomSize != null) {
            stmt.bindString(24, deviceRomSize);
        }
 
        String deviceRomAvailableSize = entity.getDeviceRomAvailableSize();
        if (deviceRomAvailableSize != null) {
            stmt.bindString(25, deviceRomAvailableSize);
        }
 
        String deviceRamMaxSize = entity.getDeviceRamMaxSize();
        if (deviceRamMaxSize != null) {
            stmt.bindString(26, deviceRamMaxSize);
        }
 
        String deviceRamTotalSize = entity.getDeviceRamTotalSize();
        if (deviceRamTotalSize != null) {
            stmt.bindString(27, deviceRamTotalSize);
        }
 
        String deviceRamUseSize = entity.getDeviceRamUseSize();
        if (deviceRamUseSize != null) {
            stmt.bindString(28, deviceRamUseSize);
        }
        stmt.bindLong(29, entity.getDeviceCpuTemperature());
        stmt.bindLong(30, entity.getDeviceTemperature());
 
        String deviceSystemVersion = entity.getDeviceSystemVersion();
        if (deviceSystemVersion != null) {
            stmt.bindString(31, deviceSystemVersion);
        }
 
        String deviceAppVersion = entity.getDeviceAppVersion();
        if (deviceAppVersion != null) {
            stmt.bindString(32, deviceAppVersion);
        }
 
        String deviceCameraSdkVersion = entity.getDeviceCameraSdkVersion();
        if (deviceCameraSdkVersion != null) {
            stmt.bindString(33, deviceCameraSdkVersion);
        }
 
        String deviceHardwareSdkVersion = entity.getDeviceHardwareSdkVersion();
        if (deviceHardwareSdkVersion != null) {
            stmt.bindString(34, deviceHardwareSdkVersion);
        }
 
        String deviceElapsedRealtime = entity.getDeviceElapsedRealtime();
        if (deviceElapsedRealtime != null) {
            stmt.bindString(35, deviceElapsedRealtime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TestBean readEntity(Cursor cursor, int offset) {
        TestBean entity = new TestBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // cameraDetectType
            cursor.getDouble(offset + 2), // faceFeaturePairNumber
            cursor.getInt(offset + 3), // faceFeaturePairSuccessOrFailWaitTime
            cursor.getInt(offset + 4), // openDoorType
            cursor.getInt(offset + 5), // openDoorContinueTime
            cursor.getInt(offset + 6), // doorType
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // deviceName
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // deviceSerialNumber
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // deviceDefendStartTime
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // deviceDefendEndTime
            cursor.getInt(offset + 11), // deviceIntoOrOut
            cursor.getInt(offset + 12), // deviceMusicSize
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // appWelcomeMsg
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // appWelcomeMusic
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // serverIp
            cursor.getInt(offset + 16), // serverPort
            cursor.getInt(offset + 17), // deviceNetworkType
            cursor.getInt(offset + 18), // deviceNetworkIpType
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // deviceIpAddress
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // deviceSn
            cursor.getInt(offset + 21), // deviceServiceTime
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // deviceRegisterTime
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // deviceRomSize
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // deviceRomAvailableSize
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // deviceRamMaxSize
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // deviceRamTotalSize
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // deviceRamUseSize
            cursor.getInt(offset + 28), // deviceCpuTemperature
            cursor.getInt(offset + 29), // deviceTemperature
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // deviceSystemVersion
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // deviceAppVersion
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // deviceCameraSdkVersion
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // deviceHardwareSdkVersion
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34) // deviceElapsedRealtime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TestBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCameraDetectType(cursor.getInt(offset + 1));
        entity.setFaceFeaturePairNumber(cursor.getDouble(offset + 2));
        entity.setFaceFeaturePairSuccessOrFailWaitTime(cursor.getInt(offset + 3));
        entity.setOpenDoorType(cursor.getInt(offset + 4));
        entity.setOpenDoorContinueTime(cursor.getInt(offset + 5));
        entity.setDoorType(cursor.getInt(offset + 6));
        entity.setDeviceName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDeviceSerialNumber(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDeviceDefendStartTime(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setDeviceDefendEndTime(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setDeviceIntoOrOut(cursor.getInt(offset + 11));
        entity.setDeviceMusicSize(cursor.getInt(offset + 12));
        entity.setAppWelcomeMsg(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setAppWelcomeMusic(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setServerIp(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setServerPort(cursor.getInt(offset + 16));
        entity.setDeviceNetworkType(cursor.getInt(offset + 17));
        entity.setDeviceNetworkIpType(cursor.getInt(offset + 18));
        entity.setDeviceIpAddress(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setDeviceSn(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setDeviceServiceTime(cursor.getInt(offset + 21));
        entity.setDeviceRegisterTime(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setDeviceRomSize(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setDeviceRomAvailableSize(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setDeviceRamMaxSize(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setDeviceRamTotalSize(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setDeviceRamUseSize(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setDeviceCpuTemperature(cursor.getInt(offset + 28));
        entity.setDeviceTemperature(cursor.getInt(offset + 29));
        entity.setDeviceSystemVersion(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setDeviceAppVersion(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setDeviceCameraSdkVersion(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setDeviceHardwareSdkVersion(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setDeviceElapsedRealtime(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TestBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TestBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
